### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Waller1337** [michikxd/hourbooster#1]
Hi,
It is possible to run acc with mobile token without shared code on vps beacuase when i run with forver script (forever start bot.js)  it is not possible to enter the code

**Comment by michikxd** [comment]
I use it on VPS, and just turn on the script with "node bot.js" and then write the code.

**Comment by Waller1337** [comment]
But how can i create a screen ?

**Comment by michikxd** [comment]
https://www.youtube.com/watch?v=RdaFll2HaRQ&ab_channel=LinuxTechShow

Check this video.

**Comment by michikxd** [comment]
I made a readme for linux. You have everything there. 
https://github.com/michikxd/hourbooster/blob/master/ReadMeLinux
