### ISSUE TITLE
Steam profiles appears as non-Steam game

### ISSUE THREAD

**Issue by alvitodev** [michikxd/hourbooster#10]
i use these config and it should appear as counter strike: global offensive, but its showing non-steam games.
`"settings": {
                "title": [ "csgo" ],
                "games": [ 730 ]
            }`

![image](https://user-images.githubusercontent.com/70482031/148236304-1fe27af0-b199-4514-ae22-93415d5e0d19.png)

**Comment by michikxd** [comment]
Hey, set it like this to remove the custom title.
```json
"settings": {
    "title": [ ],
    "games": [ 730 ]
}  
```

**Comment by alvitodev** [comment]
Thanks it works!!
