### ISSUE TITLE
repl.it issue

### ISSUE THREAD

**Issue by PanSmuggler** [michikxd/hourbooster#2]
when i run it on repl.it website it log into acc but doesn't idle games and dont show status
Any ideas how to fix or what is issue?

here is terminal code:

`node v12.16.1

 

Repl.it: Updating package configuration

--> npm init -y
Wrote to /home/runner/SupportiveEnviousWordprocessing/package.json:

{
SteamUser {
  _events: [Object: null prototype] { loggedOn: [Function] },
  _eventsCount: 1,
  _maxListeners: undefined,
  steamID: null,
  chat: SteamChatRoomClient { user: [Circular] },
  limitations: null,
  vac: null,
  wallet: null,
  emailInfo: null,
  licenses: null,
  gifts: null,
  users: {},
  groups: {},
  chats: {},
  myFriends: {},
  myGroups: {},
  myFriendGroups: {},
  myNicknames: {},
  steamServers: {},
  contentServersReady: false,
  playingState: { blocked: false, appid: 0 },
  _playingBlocked: false,
  _playingAppIds: [],
  _gcTokens: [],
  _connectTime: 0,
  _connectionCount: 0,
  _connectTimeout: 1000,
  _authSeqMe: 0,
  _authSeqThem: 0,
  _hSteamPipe: 678914,
  _contentServers: [],
  _contentServersTimestamp: 0,
  _contentServerTokens: {},
  _lastNotificationCounts: {},
  _sessionID: 0,
  _jobs: {},
  _richPresenceLocalization: {},
  _initialized: true,
  _changelistUpdateTimer: null,
  picsCache: { changenumber: 0, apps: {}, packages: {} },
  _sentry: null,
  options: {
    protocol: 0,
    httpProxy: null,
    localAddress: null,
    localPort: null,
    autoRelogin: true,
    singleSentryfile: false,
    machineIdType: 3,
    machineIdFormat: [
      'SteamUser Hash BB3 {account_name}',
      'SteamUser Hash FF2 {account_name}',
      'SteamUser Hash 3B3 {account_name}'
    ],
    enablePicsCache: false,
    picsCacheAll: false,
    changelistUpdateInterval: 60000,
    saveAppTickets: true,
    additionalHeaders: {},
    language: 'english',
    webCompatibilityMode: false,
    dataDirectory: '/home/runner/.local/share/node-steamuser'
  },
  storage: FileManager {
    _directory: '/home/runner/.local/share/node-steamuser'
  },
  [Symbol(kCapture)]: false
}
Hint: hit control+c anytime to enter REPL.
Steam Guard App Code: xxxxx
account You has been logged succesfully.`

**Comment by michikxd** [comment]
I think you didn't install the modules. 

`npm install steam-user`

**Comment by Boryyy** [comment]
how to make it run like 24 hours , its not working for me , https://uptimerobot.com/ doesnt make it run 24 hours , only like 30 mins :|

**Comment by michikxd** [comment]
I recommend to buy a VPS server with linux, and host it there. Im using [this one](https://evolution-host.com/vps-hosting.php) starter pack. [Here](https://github.com/michikxd/hourbooster/blob/master/ReadMeLinux) you can check my linux guide.

**Comment by Boryyy** [comment]
@michikxd how do i get shared secret without the pc version one ? can u help me , i will add u in discord if u want.

**Comment by PanSmuggler** [comment]
> I think that you didn't install the modules.
> 
> `npm install steam-user`

probably repl.it didn't installed it

**Comment by Boryyy** [comment]
@PanSmuggler try again

**Comment by michikxd** [comment]
> @michikxd how do i get shared secret without the pc version one ? can u help me , i will add u in discord if u want.

You have to have SDA (Steam Desktop Authenticator) if you want to get shared secret. My discord is MichiK#0848

**Comment by michikxd** [comment]
> > I think that you didn't install the modules.
> > `npm install steam-user`
> 
> probably repl.it didn't installed it

I think that repl.it doesn't support the npm.

**Comment by Boryyy** [comment]
@michikxd it does , im doing it with repl.it

**Comment by PanSmuggler** [comment]
> @michikxd how do i get shared secret without the pc version one ? can u help me , i will add u in discord if u want.

try with idle daddy (google play store) to get shared secret from steam app
you will need root on your phone
