### ISSUE TITLE
Idle offline

### ISSUE THREAD

**Issue by Primoszz** [michikxd/hourbooster#6]
How to go offline on steam? Idle offline?

**Comment by TheBrokennWorld** [comment]
> How to go offline on steam? Idle offline?

Try changing EPersonaState in bot.js to some value from this [list](https://github.com/DoctorMcKay/node-steam-user/blob/master/enums/EPersonaState.js)

**Comment by michikxd** [comment]
Just edit the "EPersonaState" value as @TheBrokennWorld mentioned before.
