### ISSUE TITLE
More than one steam account

### ISSUE THREAD

**Issue by Primoszz** [michikxd/hourbooster#7]
How can I run more than 1 account? On VPS.

**Comment by Boryyy** [comment]
10 accounts ,run the code 10 times with the each in account config?

**Comment by michikxd** [comment]
Hi Primoszz, 
you can run the script multiple times.
Also I'm about to push a new version of this script which is way to more advanced, unlike this simple one. I already done it few weeks ago, but I didn't release it yet, due to some complications.

**Comment by Primoszz** [comment]
Okay. Thank you!
I'm waiting for a new release :)
