### ISSUE TITLE
The bot crashes when you open steam chat

### ISSUE THREAD

**Issue by Primoszz** [michikxd/hourbooster#8]
I have a bot running on windows. When entering the application on the phone, the bot turns off. Can it be prevented somehow?

**Comment by michikxd** [comment]
Hi, 
please provide the output of console when it does this.

**Comment by Primoszz** [comment]
The bot is working fine. When I turn on the steam chat application on my phone, the bot on the computer turns off with the console.

**Comment by michikxd** [comment]
Don't run the bot via `start.bat` file but open console and run it manually.

**Comment by Primoszz** [comment]
https://i.imgur.com/fX0jwD6.png
